version: "3.8"

services:
  userservice:
    build: ./UserService
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  consumerservice:
    build: ./ConsumerService
    depends_on:
      - userservice
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
